import { createAudioPlayer, type AudioPlayer } from 'expo-audio';

import { getSession } from './session';

// Generated by scripts/generate-sounds.mjs.
const SOURCES = {
  right: require('../../assets/sounds/right.wav'),
  wrong: require('../../assets/sounds/wrong.wav'),
  finish: require('../../assets/sounds/finish.wav'),
};

export type SoundName = keyof typeof SOURCES;

/** How long the right/wrong chime rings before spoken Spanish starts, so the two don't overlap. */
export const CHIME_MS = 380;

// One player per sound, made on first use and kept for the life of the app: short, frequent sounds.
const players = new Map<SoundName, AudioPlayer>();

/** Plays a lesson sound, unless the learner turned "Sound effects" off. */
export function playSound(name: SoundName) {
  if (!getSession().soundEffects) return;
  try {
    let player = players.get(name);
    if (!player) {
      player = createAudioPlayer(SOURCES[name]);
      players.set(name, player);
    }
    player.seekTo(0);
    player.play();
  } catch {
    // A missing sound never gets in the way of the lesson.
  }
}
