/**
 * Cielo's built-in phrase bank: common chat English → natural, casual Latin American Spanish (tú).
 *
 * Written for how people actually text, not word for word: "did you eat" → "¿Ya comiste?".
 * Keys use the brain's normalized form: lowercase, slang expanded, straight apostrophes, no punctuation.
 *
 * Alternatives carry a `when` label:
 *   F      the speaker is a woman ("Estoy cansada")
 *   HER    said to a woman ("Eres hermosa")
 *   SPAIN  how Spain says it
 *   or a short free-text label.
 */

export type Alt = [es: string, when: string];
export type Entry = { en: string; es: string; alts?: Alt[]; note?: string };

const F = "if you're a woman";
const HER = 'to a woman';
const SPAIN = 'in Spain';

const e = (en: string, es: string, alts?: Alt[], note?: string): Entry => ({ en, es, alts, note });
/** Speaker-gendered: "Estoy cansad" + o/a. */
const g = (en: string, stem: string, rest = ''): Entry => e(en, `${stem}o${rest}`, [[`${stem}a${rest}`, F]]);
/** Listener-gendered: "Eres hermos" + o/a. */
const toG = (en: string, stem: string, rest = ''): Entry => e(en, `${stem}o${rest}`, [[`${stem}a${rest}`, HER]]);

export const PHRASES: Entry[] = [
  // Hello and goodnight
  e('good morning', 'Buenos días'),
  e('good afternoon', 'Buenas tardes'),
  e('good evening', 'Buenas noches'),
  e('good night', 'Buenas noches'),
  e('hello', 'Hola'),
  e('hi', 'Hola'),
  e('hey', 'Hola', [['Oye', 'to get their attention']]),
  e('bye', 'Chao', [['Adiós', 'more formal']]),
  e('goodbye', 'Adiós'),
  e('see you', 'Nos vemos'),
  e('see you later', 'Nos vemos luego'),
  e('see you soon', 'Nos vemos pronto'),
  e('see you tomorrow', 'Nos vemos mañana'),
  e('see you this weekend', 'Nos vemos este fin de semana'),
  e('talk to you later', 'Hablamos luego'),
  e('sweet dreams', 'Dulces sueños'),
  e('sleep well', 'Que duermas bien'),
  e('did you sleep well', '¿Dormiste bien?'),
  e('i slept well', 'Dormí bien'),
  e('i slept so well', 'Dormí muy bien'),
  e('how are you', '¿Cómo estás?'),
  e('how are you doing', '¿Cómo te va?'),
  e('how are you today', '¿Cómo estás hoy?'),
  e('how was your day', '¿Cómo te fue hoy?'),
  e('how was work', '¿Cómo te fue en el trabajo?'),
  e('how about you', '¿Y tú?'),
  e('what about you', '¿Y tú?'),
  e('and you', '¿Y tú?'),
  e("i'm good", 'Estoy bien'),
  e("i'm fine", 'Estoy bien'),
  e("i'm okay", 'Estoy bien'),
  e("i'm great", 'Estoy muy bien'),
  e('not bad', 'No está mal'),
  e("what's up", '¿Qué tal?'),
  e('what are you doing', '¿Qué haces?'),
  e('what are you up to', '¿Qué estás haciendo?'),
  e('nothing much', 'Nada, aquí'),
  e('are you there', '¿Estás ahí?'),
  toG('are you awake', '¿Estás despiert', '?'),
  e('are you okay', '¿Estás bien?'),
  e('are you home', '¿Estás en casa?'),
  e('are you free', '¿Estás libre?'),
  g("i'm awake", 'Estoy despiert'),
  e("i'm going to sleep", 'Me voy a dormir'),
  e("i'm going to bed", 'Me voy a la cama'),
  e('go to sleep', 'Vete a dormir'),
  e('wake up', 'Despierta'),
  e('i just woke up', 'Me acabo de despertar'),

  // Sweet words
  e('i love you', 'Te quiero', [['Te amo', 'deep, romantic love']], '"Te quiero" is everyday love — for partners, family and friends. "Te amo" is deeper and mostly romantic.'),
  e('i love you so much', 'Te quiero muchísimo', [['Te amo muchísimo', 'deep, romantic love']]),
  e('i love you too', 'Yo también te quiero', [['Yo también te amo', 'deep, romantic love']]),
  e('i love you more', 'Yo te quiero más', [['Yo te amo más', 'deep, romantic love']]),
  e('love you', 'Te quiero'),
  e('love you more', 'Te quiero más'),
  e('i miss you', 'Te extraño', [['Te echo de menos', SPAIN]]),
  e('i miss you so much', 'Te extraño muchísimo', [['Te echo mucho de menos', SPAIN]]),
  e('i miss you too', 'Yo también te extraño'),
  e('i miss you more', 'Yo te extraño más'),
  e('miss you', 'Te extraño'),
  e('i need you', 'Te necesito'),
  e('i want to see you', 'Quiero verte'),
  e("i can't wait to see you", 'Tengo muchas ganas de verte', undefined, 'Spanish says "I have a lot of wanting to see you" — it sounds warm, not impatient.'),
  e("can't wait to see you", '¡Qué ganas de verte!'),
  e("i can't wait", '¡Qué ganas!'),
  e('thinking of you', 'Pienso en ti'),
  e("i'm thinking of you", 'Estoy pensando en ti'),
  e('i was thinking of you', 'Estaba pensando en ti'),
  toG("you're beautiful", 'Eres hermos'),
  toG("you're so cute", 'Eres muy lind'),
  toG('you look beautiful', 'Te ves hermos'),
  e("you're the best", 'Eres el mejor', [['Eres la mejor', HER]]),
  e('my love', 'Mi amor'),
  e('kisses', 'Besos'),
  e('hugs', 'Abrazos'),
  e('you make me happy', 'Me haces feliz'),
  g("i'm proud of you", 'Estoy orgullos', ' de ti'),
  e("i'm sorry", 'Lo siento'),
  e("i'm so sorry", 'Lo siento mucho'),
  e("it's okay", 'Está bien'),
  e("don't worry", 'No te preocupes'),
  e('no worries', 'No pasa nada'),
  e('thank you', 'Gracias'),
  e('thank you so much', 'Muchísimas gracias'),
  e("you're welcome", 'De nada'),
  e('no problem', 'No hay problema'),

  // Did you eat?
  e('did you eat', '¿Ya comiste?', undefined, 'Literally "did you already eat?" — the "ya" makes it sound caring and natural.'),
  e('have you eaten', '¿Ya comiste?'),
  e('did you eat lunch', '¿Ya almorzaste?'),
  e('did you have lunch', '¿Ya almorzaste?'),
  e('did you eat dinner', '¿Ya cenaste?'),
  e('did you have dinner', '¿Ya cenaste?'),
  e('did you have breakfast', '¿Ya desayunaste?'),
  e('what did you eat', '¿Qué comiste?'),
  e("i'm hungry", 'Tengo hambre', undefined, 'Spanish says "I have hunger" rather than "I am hungry".'),
  e("i'm so hungry", 'Tengo mucha hambre'),
  e("i'm eating", 'Estoy comiendo'),
  e("i'm eating now", 'Estoy comiendo ahora'),
  e("let's eat", 'Vamos a comer'),
  e('what do you want to eat', '¿Qué quieres comer?'),
  e('what do you want for dinner', '¿Qué quieres cenar?'),
  e("i'm cooking", 'Estoy cocinando'),
  g("i'm full", 'Estoy llen'),
  e("i'm thirsty", 'Tengo sed'),
  e("don't skip lunch", 'No te saltes el almuerzo'),

  // On my way
  e('on my way', 'Voy en camino'),
  e("i'm on my way", 'Voy en camino'),
  e('on my way home', 'Voy camino a casa'),
  e("i'm on my way home", 'Voy camino a casa'),
  e("i'm home", 'Ya llegué a casa', undefined, 'Literally "I already arrived home" — how Spanish speakers say they made it back.'),
  e("i'm at home", 'Estoy en casa'),
  e("i'm here", 'Ya estoy aquí'),
  e("i'm almost there", 'Ya casi llego'),
  e("i'm outside", 'Estoy afuera'),
  e('where are you', '¿Dónde estás?'),
  e('when are you coming', '¿Cuándo vienes?'),
  e('are you coming', '¿Vienes?'),
  e('come home', 'Ven a casa'),
  e('come here', 'Ven acá', [['Ven aquí', SPAIN]]),
  e("i'm coming", 'Ya voy'),
  e("i'll be there soon", 'Llego pronto'),
  e("i'll be late", 'Voy a llegar tarde'),
  e("i'm running late", 'Voy tarde'),
  e('text me when you get home', 'Avísame cuando llegues a casa'),
  e('text me', 'Escríbeme'),
  e('let me know', 'Avísame'),
  e('call me', 'Llámame'),
  e('call me later', 'Llámame más tarde'),
  e("call me when you're free", 'Llámame cuando estés libre'),
  e("i'll call you later", 'Te llamo más tarde'),
  e('i will call you later', 'Te llamo más tarde'),
  e("i'll call you", 'Te llamo'),
  e('can i call you', '¿Te puedo llamar?'),
  e('can you call me', '¿Me puedes llamar?'),
  g("i'm busy", 'Estoy ocupad'),
  e("i'm at work", 'Estoy en el trabajo'),
  e("i'm going to work", 'Me voy al trabajo'),
  e("i'm leaving work", 'Ya salgo del trabajo'),
  e('what are we doing tonight', '¿Qué hacemos esta noche?'),
  e("let's go", 'Vamos'),
  e('wait for me', 'Espérame'),
  e('hurry up', 'Apúrate', [['Date prisa', SPAIN]]),
  g("i'm ready", 'Estoy list'),
  toG('are you ready', '¿Estás list', '?'),
  e('right now', 'Ahora mismo'),
  e('this weekend', 'Este fin de semana'),

  // How you feel
  g("i'm tired", 'Estoy cansad'),
  g("i'm so tired", 'Estoy muy cansad'),
  g("i'm bored", 'Estoy aburrid'),
  e("i'm happy", 'Estoy feliz'),
  e("i'm so happy", 'Estoy muy feliz'),
  e("i'm sad", 'Estoy triste'),
  g("i'm sick", 'Estoy enferm'),
  g("i'm stressed", 'Estoy estresad'),
  g("i'm excited", 'Estoy emocionad'),
  e("i'm sleepy", 'Tengo sueño'),
  e("i'm cold", 'Tengo frío'),
  e("i'm hot", 'Tengo calor'),
  e('i feel better', 'Me siento mejor'),
  e("i don't feel well", 'No me siento bien'),
  e('are you feeling better', '¿Te sientes mejor?'),
  e('me too', 'Yo también'),
  e("i can't sleep", 'No puedo dormir'),
  e("can't sleep", 'No puedo dormir'),

  // First steps: the basics every beginner needs (also used by Day 0, "Primeros pasos")
  e('yes', 'Sí'),
  e('no', 'No'),
  e("i'm not well", 'Estoy mal', [['No estoy bien', 'also common']]),
  e("what's your name", '¿Cómo te llamas?', undefined, 'Literally "how do you call yourself?"'),
  e('nice to meet you', 'Mucho gusto'),
  e("i don't understand", 'No entiendo'),
  e('can you repeat', '¿Puedes repetir?'),
  e('more slowly please', 'Más despacio, por favor'),
  e('how do you say', '¿Cómo se dice?', undefined, 'Add the word you need: "¿Cómo se dice «love» en español?"'),
  e('what does that mean', '¿Qué significa eso?'),
  e('i want water', 'Quiero agua', undefined, 'A pattern you can reuse: Quiero + anything you want. Quiero comer, quiero verte.'),
  e('i need help', 'Necesito ayuda', undefined, 'Necesito + anything you need. Necesito dormir, necesito un abrazo.'),
  e('i have a question', 'Tengo una pregunta', undefined, 'Tengo means "I have". Spanish also uses it for feelings: tengo hambre, tengo sueño.'),
  e('i like music', 'Me gusta la música', undefined, 'Literally "music pleases me". Me gusta + what you like; no me gusta for what you don\'t.'),

  // Everyday replies
  e('i know', 'Ya sé'),
  e("i don't know", 'No sé'),
  e("i don't care", 'Me da igual'),
  e('i think so', 'Creo que sí'),
  e("i don't think so", 'Creo que no'),
  e('of course', 'Claro'),
  e('for real', '¿En serio?'),
  toG('are you sure', '¿Estás segur', '?'),
  e('good idea', 'Buena idea'),
  e("that's good", 'Qué bien'),
  e("that's great", '¡Qué bueno!'),
  e("that's funny", '¡Qué chistoso!', [['¡Qué gracioso!', SPAIN]]),
  e("that's crazy", '¡Qué locura!'),
  e('oh my god', '¡Dios mío!'),
  e('just kidding', 'Es broma'),
  e('never mind', 'No importa'),
  e('hold on', 'Espera un momento'),
  e('one second', 'Un segundo'),
  e('what do you mean', '¿Qué quieres decir?'),
  e('what happened', '¿Qué pasó?'),
  e('what time', '¿A qué hora?'),
  e('what time is it', '¿Qué hora es?'),
  e("i'll tell you later", 'Luego te cuento'),
  e('tell me', 'Cuéntame'),
  e('good luck', 'Buena suerte'),
  e('happy birthday', '¡Feliz cumpleaños!'),
  e('take care', 'Cuídate'),
  e('be careful', 'Ten cuidado'),
  e('drive safe', 'Maneja con cuidado'),
  e('have a good day', 'Que tengas un buen día'),
  e('have a nice day', 'Que tengas un lindo día'),
  e('have fun', 'Diviértete'),
  e('surprise me', 'Sorpréndeme'),
  e('check this out', 'Mira esto'),
  e('look at this', 'Mira esto'),
  e('send me a picture', 'Mándame una foto'),
  e("i'm watching a movie", 'Estoy viendo una película'),
  e('what are you watching', '¿Qué estás viendo?'),
];

/** Single words, shown with their article (nouns) or as "to ..." (verbs) so they make sense alone. */
export const WORDS: Entry[] = [
  // People and pet names
  e('babe', 'amor', [['bebé', 'also common']], 'The most natural pet name in Spanish is simply "amor" (love).'),
  e('baby', 'bebé', [['amor', 'as a pet name']]),
  e('honey', 'cariño'),
  e('love', 'el amor', undefined, 'The noun. "I love you" is "te quiero".'),
  e('friend', 'el amigo', [['la amiga', 'a female friend']]),
  e('family', 'la familia'),
  e('mom', 'mamá'),
  e('dad', 'papá'),
  e('sister', 'la hermana'),
  e('brother', 'el hermano'),
  e('kiss', 'el beso'),
  e('hug', 'el abrazo'),
  e('heart', 'el corazón'),

  // Feelings and descriptions
  toG('beautiful', 'hermos'),
  toG('cute', 'lind'),
  e('happy', 'feliz'),
  e('sad', 'triste'),
  g('tired', 'cansad'),
  g('busy', 'ocupad'),
  g('ready', 'list'),
  e('free', 'libre'),
  e('good', 'bueno'),
  e('bad', 'malo'),
  e('great', 'genial'),
  e('nice', 'lindo'),
  e('amazing', 'increíble'),
  e('funny', 'chistoso'),
  e('crazy', 'loco'),
  e('sweet', 'dulce'),
  e('late', 'tarde'),
  e('well', 'bien'),
  e('so much', 'muchísimo', [['tanto', 'also common']]),
  e('early', 'temprano'),
  e('sorry', 'perdón'),
  e('thanks', 'gracias'),
  e('please', 'por favor'),
  e('hungry', 'con hambre', undefined, 'Usually said with "tener": "tengo hambre".'),

  // Time
  e('today', 'hoy'),
  e('tomorrow', 'mañana'),
  e('yesterday', 'ayer'),
  e('tonight', 'esta noche'),
  e('later', 'más tarde', [['luego', 'also common']]),
  e('soon', 'pronto'),
  e('morning', 'la mañana'),
  e('afternoon', 'la tarde'),
  e('night', 'la noche'),
  e('day', 'el día'),
  e('week', 'la semana'),
  e('weekend', 'el fin de semana'),
  e('birthday', 'el cumpleaños'),

  // Places and things
  e('home', 'la casa', undefined, 'Going home is "a casa"; being home is "en casa".'),
  e('house', 'la casa'),
  e('work', 'el trabajo'),
  e('office', 'la oficina'),
  e('gym', 'el gimnasio'),
  e('school', 'la escuela'),
  e('class', 'la clase'),
  e('room', 'el cuarto'),
  e('bed', 'la cama'),
  e('kitchen', 'la cocina'),
  e('store', 'la tienda'),
  e('city', 'la ciudad'),
  e('trip', 'el viaje'),
  e('flight', 'el vuelo'),
  e('airport', 'el aeropuerto'),
  e('car', 'el carro', [['el coche', SPAIN]]),
  e('phone', 'el teléfono'),
  e('message', 'el mensaje'),
  e('picture', 'la foto'),
  e('photo', 'la foto'),
  e('movie', 'la película'),
  e('music', 'la música'),
  e('party', 'la fiesta'),
  e('gift', 'el regalo'),
  e('money', 'el dinero'),
  e('dog', 'el perro'),
  e('cat', 'el gato'),
  e('weather', 'el clima'),
  e('rain', 'la lluvia'),
  e('doctor', 'el médico'),

  // Food
  e('food', 'la comida'),
  e('breakfast', 'el desayuno'),
  e('lunch', 'el almuerzo'),
  e('dinner', 'la cena'),
  e('coffee', 'el café'),
  e('tea', 'el té'),
  e('water', 'el agua', undefined, 'Feminine, but takes "el" because it starts with a stressed "a".'),
  e('rice', 'el arroz'),
  e('pasta', 'la pasta'),
  e('pizza', 'la pizza'),
  e('chicken', 'el pollo'),
  e('bread', 'el pan'),

  // Actions
  e('eat', 'comer', undefined, 'to eat'),
  e('sleep', 'dormir', undefined, 'to sleep'),
  e('call', 'llamar', undefined, 'to call'),
  e('miss', 'extrañar', undefined, 'to miss someone'),
  e('talk', 'hablar', undefined, 'to talk'),
  e('see', 'ver', undefined, 'to see'),
  e('come', 'venir', undefined, 'to come'),
  e('go', 'ir', undefined, 'to go'),
  e('want', 'querer', undefined, 'to want'),
  e('need', 'necesitar', undefined, 'to need'),
  e('know', 'saber', undefined, 'to know (a fact)'),
  e('think', 'pensar', undefined, 'to think'),
  e('feel', 'sentir', undefined, 'to feel'),
  e('wait', 'esperar', undefined, 'to wait'),
  e('cook', 'cocinar', undefined, 'to cook'),
  e('drive', 'manejar', [['conducir', SPAIN]], 'to drive'),
  e('watch', 'ver', undefined, 'to watch'),
  e('listen', 'escuchar', undefined, 'to listen'),
  e('play', 'jugar', undefined, 'to play'),
  e('buy', 'comprar', undefined, 'to buy'),
  e('pay', 'pagar', undefined, 'to pay'),
  e('walk', 'caminar', undefined, 'to walk'),
  e('read', 'leer', undefined, 'to read'),
  e('write', 'escribir', undefined, 'to write'),
  e('help', 'ayudar', undefined, 'to help'),
  e('remember', 'recordar', undefined, 'to remember'),
  e('forget', 'olvidar', undefined, 'to forget'),
  e('tell', 'decir', undefined, 'to tell'),
  e('send', 'mandar', undefined, 'to send'),
  e('text', 'escribir', undefined, 'to text — Spanish just says "to write"'),
];
